{% set name = "diffrax" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9290649ea8241e36794c9371a488a51d02ee8326e2e065f13e7331d6f1a3f7af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - jax >=0.2.27
    - jaxlib >=0.1.76
    - equinox >=0.1.6

test:
  imports:
    - diffrax
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/patrick-kidger/diffrax
  summary: Numerical differential equation solvers in JAX.
  description: |
    Numerical differential equation solvers in JAX. Autodifferentiable and GPU-capable.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.kidger.site/diffrax/
  dev_url: https://github.com/patrick-kidger/diffrax

extra:
  recipe-maintainers:
    - dhirschfeld
